spring:          
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: warehouse-configserver-dev


---
spring:
  profiles: test
  application:
    name: warehouse-configserver-test1   


#保存為utf-8 